---
title: "Plot of latencies to open the door of the test compartment to release the trapped pig"
author: "Liza Moscovice, Anja Eggert, Christian Manteuffel and Jean-Loup Rault"
date: "`r Sys.Date()`" 
editor: visual
code-fold: false
toc: true
format: html
self-contained: true
---

# Libraries

```{r, libraries, warning=FALSE, message=FALSE, echo=TRUE}
library(tidyverse)     # tidy universe
library(viridis)       # viridis colours
```

```{r, my_theme, echo = FALSE}
my_theme = theme_classic() +
  theme(axis.title = element_text(face = "bold", size = 14),
        axis.text  = element_text(size = 12, angle = 0, vjust = 0.5),
        plot.title = element_text(face = "bold", size = 14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```

```{r, seed}
set.seed(1989)
```

# Data

## Read data

```{r, data, warning = FALSE}
dat <- read_csv("../data/Fig-S6-latency-trials.csv")
```

## Adjust data types

```{r, data-adj}
dat <- dat %>% 
  mutate_at(vars(trapped.order), ~as.factor(.))
```

## Data summary

```{r, data-sum}
dat %>% 
  filter( helper == "Pig") %>% 
  group_by(trapped.order)%>%
  rstatix::get_summary_stats(c(lat.helped.min), 
                             show = c("mean", "sd", 
                                      "min", "max", 
                                      "median", "iqr")) %>% 
  ungroup()
```

# Plot

```{r, plot-1}
plot <- dat %>%
  ggplot() +
  geom_boxplot(data = subset(dat, helper == "Pig"),
               aes(x = trapped.order, 
                   y = lat.helped.min),
               outlier.shape = NA, width = 0.5, col = "orchid", 
               show.legend = FALSE) +
  geom_point(aes(x     = trapped.order, 
                 y     = lat.helped.min,
                 col   = id.group,
                 shape = helper),
             position = position_jitterdodge(jitter.width  = 0.15,
                                             jitter.height = 0.0,
                                             dodge.width   = 0.2),
             size = 3, alpha = 0.5) +
  scale_shape_manual(values = c(17, 19),
                     labels = c("Pig released by researcher", 
                                "Pig released by helper")) +
  scale_color_manual(values = viridis(n=8),
                     guide="none") +
  scale_y_continuous(lim = c(0, 20.01), breaks = seq(0, 20, 5)) +
  labs(x = "Test trial",
       y = "Latency to first open door (min)") +
  my_theme +
  guides(shape = guide_legend(override.aes = list(size  = 4,
                                                  shape = c(17, 19)))) +
  theme(legend.justification = c(1,0.6),
        legend.position = c(1,0.6),
        legend.background = element_rect(fill = NA,
                                         colour ="black",
                                         size=0.3,
                                         linetype="solid"),
        legend.title = element_blank(),
        legend.text = element_text(size=12))
```

```{r, plot-2, fig.height=10, fig.width=10, warning=FALSE}
plot
```

# How to cite R

"All analyses were performed using R Statistical Software (version 4.2.0; R Core Team 2022)".

Reference: R Core Team (2022). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.

```{r, cite-r}
citation()
version$version.string
```

```{r, cite-packages}
citation("tidyverse")
citation("viridis")
```

# Session Info

```{r, session}
sessionInfo()
```
