---
title: "Proportion of pigs that open door during familiarization"
author: "Liza Moscovice, Anja Eggert and Jean-Loup Rault"
date: "`r Sys.Date()`" 
editor: visual
code-fold: false
toc: true
format: html
self-contained: true
---

# Libraries

```{r, libraries, warning=FALSE, message=FALSE, echo=TRUE}
library(tidyverse)     # tidy universe
```

```{r, my_theme, echo = FALSE}
my_theme = theme_classic() +
  theme(axis.title = element_text(face="bold", size=14),
        axis.text  = element_text(size=12, angle = 0, vjust = 0.5),
        plot.title = element_text(face="bold", size=14),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())
```

```{r, seed}
set.seed(1989)
```

# Data

## Read data

```{r, data, warning = FALSE}
dat <- read_csv("../data/proportion-familiarization.csv")
```

## Adjust data types

```{r, data-adj}
dat <- dat %>%
  mutate_at(vars(type,
                 condition,
                 familiarization_day), ~as.factor(.))

dat$type = factor(dat$type, levels = c("group", "cumulative"))
```

## Data summary

```{r, data-sum}
dat %>% 
  filter(type == "group") %>% 
  group_by(familiarization_day)%>%
  rstatix::get_summary_stats(c(proportion),
                             show = c("mean", "sd", "min", "max", "median", "iqr")) %>% 
  ungroup()
```

# Plots

```{r, plot-1}
plot <- dat %>%
  ggplot() +
  geom_boxplot(data = subset(dat, type == "group"),
               aes(x     = familiarization_day,
                   y     = proportion,
                   col   = type,
                   shape = type),
               fill = NA, outlier.shape = NA, show.legend = FALSE,
               width = 0.3, position = position_nudge(x = -0.05)) +
  geom_point(data = subset(dat, type == "cumulative"),
             aes(x     = familiarization_day,
                 y     = proportion,
                 col   = type,
                 shape = type),
             size = 3,
             position = position_nudge(x = 0.0)) +
  scale_shape_manual(name = "", labels = c("Cumulative", "Within each group"),
                     values = c(16, 15)) +
  scale_colour_manual(name = "", labels = c("Cumulative", "Within each group"),
                      values = c("firebrick", "royalblue1")) +
  geom_line(data = subset(dat, type == "cumulative"),
            aes(x   = familiarization_day,
                y     = proportion,
                group = 1),
            size = 1, linetype = "dashed", col = "firebrick",
            position = position_nudge(x = 0.0)) +
  scale_y_continuous(lim = c(0, 1.05), breaks = seq(0, 1, 0.25)) +
  labs(x = "Familiarization day",
       y = "Proportion of pigs that open a door") +
  my_theme +
  theme(legend.justification = c(0.1, 0.1),
        legend.position      = c(0.1, 0.1),
        legend.background = element_rect(fill     = NA,
                                         colour   = "black",
                                         size     = 0.3,
                                         linetype = "solid"),
        legend.title = element_blank(),
        legend.text  = element_text(size = 12)) +
  guides(shape  = guide_legend(override.aes = list(alpha = 1,
                                                   size  = 4,
                                                   shape = c(16, 15))))
```

```{r, plot-2, fig.height=10, fig.width=10, warning=FALSE}
plot
```

# How to cite R

"All analyses were performed using R Statistical Software (version 4.2.0; R Core Team 2022)".

Reference: R Core Team (2022). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.

```{r, cite-r}
citation()
version$version.string
```

```{r, cite-packages}
citation("tidyverse")
```

# Session Info

```{r, session}
sessionInfo()
```
