---
title: "Testing for a location preference for opening compartments (at front or side of pen)"
author: "Liza Moscovice, Anja Eggert and Jean-Loup Rault"
date: "`r Sys.Date()`" 
editor: visual
code-fold: false
toc: true
format: html
self-contained: true
---

# Libraries

```{r, libraries, warning=FALSE, message=FALSE, echo=TRUE}
library(kableExtra)    # html tables
library(tidyverse)     # tidy universe
library(rstatix)       # binom_test()
```

# Data

## Read data

```{r, data, warning = FALSE}
dat <- read_csv("../data/side-preference-box.csv")
```

# Binomial test

## Across familiarization day

```{r, binom-test-1}
dat %>% 
  group_by(familiarization.day, location.box) %>% 
  summarize(nto = sum(number.times.opens)) %>% 
  pivot_wider(names_from = location.box, 
              values_from = nto) %>% 
  ungroup() %>% 
  # test per fam day
  group_by(familiarization.day) %>% 
  mutate(binom.p = binom_test(x = Front,
                                 n = Front + Side,
                                 p = 0.5)$p) %>% 
  ungroup() %>% 
  mutate(no. = row_number()) %>%
  relocate(no.) %>% 
  kable(caption = "Equal choice front or side per familiarization day?") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), font_size = 12) %>% 
  scroll_box(width = "500px")
```

## Across individual pigs

```{r, binom-test-2}
dat %>% 
  group_by(pig.unique.id, location.box) %>% 
  summarize(nto = sum(number.times.opens)) %>% 
  pivot_wider(names_from = location.box, 
              values_from = nto) %>% 
  replace(is.na(.), 0) %>% 
  ungroup() %>% 
  # test per fam day
  group_by(pig.unique.id) %>% 
  mutate(binom.p = binom_test(x = Front,
                                 n = Front + Side,
                                 p = 0.5)$p) %>% 
  ungroup() %>% 
  arrange(binom.p) %>% 
  mutate(no. = row_number()) %>%
  relocate(no.) %>%
  kable(caption = "Equal choice front or side per pig?") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), font_size = 12) %>% 
  scroll_box(width = "500px", height = "500px")
```

## Across social groups

```{r, binom-test-3}
dat %>% 
  group_by(unique.group, location.box) %>% 
  summarize(nto = sum(number.times.opens)) %>% 
  pivot_wider(names_from = location.box, 
              values_from = nto) %>% 
  replace(is.na(.), 0) %>% 
  ungroup() %>% 
  # test per fam day
  group_by(unique.group) %>% 
  mutate(binom.p = binom_test(x = Front,
                                 n = Front + Side,
                                 p = 0.5)$p) %>% 
  ungroup() %>% 
  arrange(binom.p) %>% 
  mutate(no. = row_number()) %>%
  relocate(no.) %>%
  kable(caption = "Equal choice front or side per group?") %>%
  kable_styling(bootstrap_options = c("striped", "hover"), font_size = 12) %>% 
  scroll_box(width = "500px")
```

# How to cite R

"All analyses were performed using R Statistical Software (version 4.2.0; R Core Team 2022)".

Reference: R Core Team (2022). R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. URL https://www.R-project.org/.

```{r, cite-r}
citation()
version$version.string
```

```{r, cite-packages}
citation("tidyverse")
citation("kableExtra")
citation("rstatix")
```

# Session Info

```{r, session}
sessionInfo()
```
